<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<PackageId>TransDataHelper</PackageId>
    <Version>0.0.1</Version>
	<Authors>GZ4nna</Authors>
	<Description>A helper library for data transfer between different databases.</Description>
	<Copyright>Copyright (c) GZ4nna. All rights reserved.</Copyright>
	<PackageTags>data transfer; database helper; cross-database; .NET</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/GZ4nna/TransDataHelper</RepositoryUrl>
	<Title>TransDataHelper</Title>
	<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	<RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdoNetCore.AseClient" Version="0.19.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.8" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Encoding\" />
    <Folder Include="Core\" />
  </ItemGroup>

</Project>
